[WIP] Proposed API changes
bcoin-org/bmultisig pull request #51
Opened 2019-04-24 20:44 UTC by BluSyn

After doing a full integration of v2 API, there are a few changes I propose.
The purpose is to simplify the API and make responses more consistent between
each other and consistent with existing bcoin APIs.

See `docs/http.md` for proposed changes to API responses.

**"Cosigner" Object on Create/Join**
Attributes with name "cosigner*" are required when creating or joining.
When viewing the wallet later, these same attributes are returned with
different attribute names (eg. `accountKey` == `cosigner.key.xpubkey`),
but sometimes the same (like `token`). This creates difficulties for clients
to make a generic "cosigner" model.

To simplify, I propose a "cosigner" object on these endpoints, to keep
everything internally and externally consistent.

**"cosignerDetails" Object**
@nodar-chkuaselidze 
Perhaps you can shed light on why `accountKey` is being returned
as `key.xpubkey` for `cosignerDetails`. Generally I think we should avoid
referring to keys as "xpub" as this can be a confusing term.
Bcoin always uses `accountKey`, plus the create/join calls, so this would
be more consistent overall. However it appears there was an intent here with
using a "key" object, but I'm not sure what it was.

Additionally, the cosigner object should ALWAYS return fields used for
derivation, (eg. `purpose`, `fingerprint`, `data`). The client needs this
in order to generate and display address paths and do signing.
The purpose of sending and storing this data is for clients to use later.
In the current API it doesn't appear there is a way to return this data?
The only "private" cosigner fields are `token` and `tokenDepth`, I believe.
@tynes  Can you confirm? Is `fingerPrint` or `data` fields potentially private?

**accountKeyProof**
I really think the server should store and return `accountKeyProof`
so clients can show this extra validation if they desire.

This also allows making `accountKeyProof` optional.
If set the server will validate. This allows clients to create "watch only"
multisig wallets, where they may not be able to provide proof. By storing
and sharing this with cosigners, we allow the clients and users to make
the decision on if this is important for their join flow.

An alternative I considered is to have a "watchOnly" flag,
that then makes `accountKeyProof` optional, but also disables signing calls.
I don't think this is a good alternative though, since that still allows for scenario
of a bad `accountKey` causing loss of funds if a user deposits.

TODO: Still need to update tests. Wanted to discuss before continuing work.

2019-04-25 18:38 UTC, nodar-chkuaselidze commented
#### Cosigner create/join

I see, it's good idea to have better naming on those so it's not confusing
when reading the code or using API.
Mostly, assumption is if you need cosigner object you can use `Cosigner.fromJSON`, but yeah,
if the names are different that's confusing.

#### Cosigner Object

  - Yeah, it seems `account` from wallet is using `hdpubkey.toBase58` instead of
  `hdpubkey.toJSON/fromJSON`, that's the reason for cosigner.key being an object.
  `HDPublicKey.toJSON` returns `{ xpubkey: ... }`
  - cosigner.key is somewhat not same as just general `accountKey`, that was the main reason
  but it makes API much better if it is `accountKey`.
  - Client only needs to know its own `purpose`, `fingerprint` and `data`. Data could be used
  for storing private information, but I don't see any problem exposing `purpose` and `fingerprint`,
  even though others can only verify that `purpose` submitted is the intended one, they can't prove
  that derivation actually used that purpose, it's just a number stored in db.

#### Account Key Proof
  Even though I think it may become the case where users will just not provide
  accountProofs if they are not required to, if we make them unable to sign
  that's a different story. Because accountKeyProof did not provide additional
  security form the servers attack vector, I decided of not saving it. But even
  if they are not able to sign and let's say they create watchOnly wallet (e.g. server
  that just notifies), as you mentioned there's a possibility of losing funds
  (even signing might not help, you may accidentally use different account or something).
  If you have all necessary informtion that you are going to provide, it should
  be easy to prove that you have accountKey. You can even do that on airgapped machine.

2019-05-04 16:37 UTC, BluSyn commented
I will think more about Account Key Proof and make it a separate PR. It's difficult to securely support all the use-cases here. For now remove that change, and focus just on the JSON format changes.

2019-05-04 18:00 UTC, BluSyn commented
Now fully tested and working. All tests pass. Removed WIP tag.

2019-05-06 19:05 UTC, tynes commented on lib/http.js
> +      const cosignerVal = new Validator(valid.obj('cosigner'), false);
The `Validator` constructor's second argument defaults to `false` already - https://github.com/bcoin-org/bval/blob/master/lib/validator.js#L28

2019-05-07 14:10 UTC, nodech requested changes
Looks good.

maybe rebase undo commits (makes commit by commit based review tough), also rebase on top of master where you can put
comments for next release. (Updated CHANGELOG.md)

2019-05-10 14:52 UTC, nodech approved these changes

2019-05-10 14:53 UTC, merged